### ISSUE TITLE
Synology NAS環境での起動について

### ISSUE THREAD

**Issue by da2el-ai** [sorshi/comistream-reader#11]
Synology NAS ではそのままでは起動できなかったので報告させていただきます。

環境：
- Synology NAS DiscStation Manager 7.2.1
- Container Manager

PHP-FPM周りで制限があったのでACLを使わないようにしたり、ディレクトリのオーナーを変更しています、
これらの変更で起動できました。

`docker-compose.yml`
```yaml:
version: '3'

services:
  comistream:
    image: ghcr.io/sorshi/comistream-reader/comistream-reader:latest
    container_name: comistream
    ports:
      - "8080:80"
    volumes:
      - /volume1/homes/{user}/comic-stream/data:/home/user/comistream/data
      - /volume1/book:/home/user/public/nas
      - ./fix_config.sh:/fix_config.sh
    restart: unless-stopped
    command: ["/usr/bin/bash", "/fix_config.sh"]
```

`fix_config.sh`
```shell:fix_config.sh
#!/usr/bin/bash  

# PHP-FPMの設定を変更
sed -i "s|listen = /run/php-fpm/www.sock|listen = 9000|g" /etc/php-fpm.d/www.conf
sed -i "s|^listen.acl_users|;listen.acl_users|g" /etc/php-fpm.d/www.conf
sed -i "s|^listen.acl_groups|;listen.acl_groups|g" /etc/php-fpm.d/www.conf

# Apacheの設定を変更
sed -i "s#proxy:unix:/run/php-fpm/www.sock|fcgi://localhost#proxy:fcgi://localhost:9000#g" /etc/httpd/conf.d/php.conf

# 権限変更
chown -R apache:apache /home/user/comistream/data
chown -R apache:apache /home/user/public/nas
chmod -R 755 /home/user/comistream/data
chmod -R 755 /home/user/public/nas

# サービスの起動
/usr/bin/bash /start.sh

```
